;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        kill-region
        org-capture
        ))

(setq mc/cmds-to-run-once
      '(
        anything-execute-extended-command
        c-toggle-auto-newline
        e2wm:dp-two-right-history-back-command
        ))
